name = "FlatGeobuf"
uuid = "d985ece1-97de-4d33-914c-38fb84042e15"
authors = ["Maarten Pronk <git@evetion.nl> and contributors"]
version = "0.1.2"

[deps]
FlatBuffers = "53afe959-3a16-52fa-a8da-cf864710bae9"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
FlatBuffers = "0.6"
Tables = "1.2"
julia = "1.6"
