# automatically generated by the FlatBuffers compiler, do not modify



FlatBuffers.@with_kw mutable struct Column
    name::String = ""
    type::ColumnType = 0
    title::String = ""
    description::String = ""
    width::Int32 = -1
    precision::Int32 = -1
    scale::Int32 = -1
    nullable::Bool = true
    unique::Bool = false
    primary_key::Bool = false
    metadata::String = ""
end
FlatBuffers.@ALIGN(Column, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T <: Column} = [
    0x00000004, 0x00000006, 0x00000008, 0x0000000A,
    0x0000000C, 0x0000000E, 0x00000010, 0x00000012,
    0x00000014, 0x00000016, 0x00000018
]

Column(buf::AbstractVector{UInt8}) = FlatBuffers.read(Column, buf)
Column(io::IO) = FlatBuffers.deserialize(io, Column)
