# automatically generated by the FlatBuffers compiler, do not modify


@enum ColumnType::UInt8 begin
    ColumnTypeByte = 0
    ColumnTypeUByte = 1
    ColumnTypeBool = 2
    ColumnTypeShort = 3
    ColumnTypeUShort = 4
    ColumnTypeInt = 5
    ColumnTypeUInt = 6
    ColumnTypeLong = 7
    ColumnTypeULong = 8
    ColumnTypeFloat = 9
    ColumnTypeDouble = 10
    ColumnTypeString = 11
    ColumnTypeJson = 12
    ColumnTypeDateTime = 13
    ColumnTypeBinary = 14
end
