# automatically generated by the FlatBuffers compiler, do not modify



FlatBuffers.@with_kw mutable struct Header
    name::String = ""
    envelope::Vector{Float64} = []
    geometry_type::GeometryType = 0
    hasZ::Bool = false
    hasM::Bool = false
    hasT::Bool = false
    hasTM::Bool = false
    columns::Vector{Column} = []
    features_count::UInt64 = 0
    index_node_size::UInt16 = 16
    crs::Crs = Crs()
    title::String = ""
    description::String = ""
    metadata::String = ""
end
FlatBuffers.@ALIGN(Header, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T <: Header} = [
    0x00000004, 0x00000006, 0x00000008, 0x0000000A,
    0x0000000C, 0x0000000E, 0x00000010, 0x00000012,
    0x00000014, 0x00000016, 0x00000018, 0x0000001A,
    0x0000001C, 0x0000001E
]
FlatBuffers.root_type(::Type{T}) where {T <: Header} = true

Header(buf::AbstractVector{UInt8}) = FlatBuffers.read(Header, buf)
Header(io::IO) = FlatBuffers.deserialize(io, Header)
