module FlatGeobuf

import FlatBuffers

# Partly autogenerated
include("schema/generated.jl")
# include("schema/feature_generated.jl")

include("flatgeobuffer.jl")
include("index.jl")
include("io.jl")
include("table.jl")

export read_file


end # module
