# if !isdefined(@__MODULE__(), :FlatGeoBuf) @__MODULE__().eval(:(module FlatGeoBuf __precompile__(false); import FlatBuffers end)) end


module FlatGeoBuf

__precompile__(false)

import FlatBuffers

# autogenerated
include("schema/GeometryType.jl")
include("schema/ColumnType.jl")
include("schema/Column.jl")
include("schema/Crs.jl")
include("schema/Geometry.jl")
include("schema/Feature.jl")
include("schema/Header.jl")


greet() = print("Hello World!")

end # module
