# automatically generated by the FlatBuffers compiler, do not modify

FlatGeoBuf.eval(quote


FlatBuffers.@with_kw mutable struct Column
    name::String = ""
    type::ColumnType = 0
end
# FlatBuffers.@ALIGN(Column, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Column} = [
    0x00000004, 0x00000006
]

Column(buf::AbstractVector{UInt8}) = FlatBuffers.read(Column, buf)
Column(io::IO) = FlatBuffers.deserialize(io, Column)

end)
