# automatically generated by the FlatBuffers compiler, do not modify

FlatGeoBuf.eval(quote

@enum GeometryType::UInt8 begin
    GeometryTypeUnknown = 0
    GeometryTypePoint = 1
    GeometryTypeLineString = 2
    GeometryTypePolygon = 3
    GeometryTypeMultiPoint = 4
    GeometryTypeMultiLineString = 5
    GeometryTypeMultiPolygon = 6
    GeometryTypeGeometryCollection = 7
    GeometryTypeCircularString = 8
    GeometryTypeCompoundCurve = 9
    GeometryTypeCurvePolygon = 10
    GeometryTypeMultiCurve = 11
    GeometryTypeMultiSurface = 12
    GeometryTypeCurve = 13
    GeometryTypeSurface = 14
    GeometryTypePolyhedralSurface = 15
    GeometryTypeTIN = 16
    GeometryTypeTriangle = 17
end


end)
